name: new_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  dartz: ^0.10.1
  equatable: ^2.0.7
  injectable: ^2.5.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  app_links: ^6.4.0



dependency_overrides:
  analyzer: ^6.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  mockito: ^5.4.5



flutter:
  uses-material-design: true

  assets:
    - assets/mocks/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

